
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSTEM_PROCESSOR "powerpc")
set(CMAKE_C_COMPILER "powerpc-linux-gnu-gcc-13")
set(CMAKE_CXX_COMPILER "powerpc-linux-gnu-g++-13")
set(CMAKE_SYSTEM_NAME "Linux")
set(CMAKE_CROSSCOMPILING ON)