name: Build
on: [pull_request]
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y libreadline-dev python3
      - name: Configure
        run: |
          ./waf configure
      - name: Build
        run: |
          ./waf build-linux  
